name = "LockOUT"
author = "HyLegacy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cf8e079029788a6686ffe59c9e76f04b84ae23f52091ffab1aec8d2f2969e62"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
