name = "LockOUT"
author = "HyLegacy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12795a6d58a94f75c6ddf057f6f195cf1d66bfc31023003bbabb61e9415a4049"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
