name = "PeruLand"
author = "HyLegacy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "151bb2f4fcb97eb42031ccd5dcfe7a6704fdcd5972e767aeb4903cb8bc4ed2d9"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
