name = "PeruLand"
author = "HyLegacy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e8c38947680acbeacc427916c61083bf0acb452d76f4489432d7be309044d3"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
