name = "PeruLand"
author = "HyLegacy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06108aead820f850b47a2133e290d05ffabc91018bac526379d4e914854544a9"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
